"""Cluster membership timing and status constants."""

HEARTBEAT_INTERVAL_SEC = 1.0
FAILURE_TIMEOUT_SEC = 3.0
FAILURE_CHECK_INTERVAL_SEC = 0.5

NODE_STATUS_UP = "UP"
NODE_STATUS_DOWN = "DOWN"

DEFAULT_METADATA_PORT = 9000
